import type { ElementsConfig, ElementsController, InternalCollector, InternalFieldBinding, InternalFrameBinding, InternalFrameStateBinding } from "./adapter";
import type { AddressMetadataState, AddressScope, BiasElementsState, BiasFieldName, PaymentMethod } from "./public-types";
import { type FrameFieldType } from "./types";
/** Framework-neutral controller. Renderer-only state stays behind this facade. */
export declare class BiasController implements ElementsController {
    private config;
    private storeState;
    private readonly store;
    private readonly listeners;
    private sessionState;
    private paymentMethod;
    private submissionStatus;
    private submissionError;
    private active;
    private generation;
    private request;
    private initialSeedConsumed;
    private completionGeneration;
    private readonly collectors;
    private readonly frames;
    private readonly validatorTokens;
    private paymentSurface;
    private reconcilingSubmission;
    private suppressSubmissionTransitions;
    private terminalError;
    constructor(config: ElementsConfig);
    getPublicState(): BiasElementsState;
    subscribe(listener: () => void): () => void;
    private notify;
    activate(): void;
    deactivate(): void;
    updateConfig(next: ElementsConfig): void;
    refreshSession(): void;
    setPaymentMethod(method: PaymentMethod): void;
    submit(): void;
    getField<K extends BiasFieldName>(name: K, scope?: AddressScope): InternalFieldBinding<K>;
    getFrame(field: FrameFieldType): InternalFrameStateBinding;
    autocompleteAddress(input: string, country: string | undefined, signal: AbortSignal): Promise<import("@biaspay/sdk").AddressAutocompleteSuggestion[]>;
    getBillingSameAsShipping(): boolean;
    setBillingSameAsShipping(value: boolean): void;
    hasCollector(kind: "contact" | "address", scope?: AddressScope): boolean;
    registerCollector(collector: InternalCollector): () => void;
    registerFrame(binding: InternalFrameBinding): () => void;
    registerPaymentElement(method?: PaymentMethod): () => void;
    getAddressMetadata(scope: AddressScope): AddressMetadataState;
    getAddressMetadataForCountry(country: string): AddressMetadataState;
    private checkoutSession;
    private canSubmit;
    private fetchSession;
    private owns;
    private applySession;
    private setTerminalError;
    private onStoreChange;
    private clearFailedSubmission;
    private relevantFieldChanged;
    private complete;
    private resolveField;
    private registerValidator;
    private applyRegistrations;
}
export type { ElementsConfig as BiasControllerConfig } from "./adapter";
